#默认使用配置
spring:
  application:
    name: sptwin
  profiles:
    active: dev
  #下面相当于CharacterEncodingFilter
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  # 下面为连接池的补充设置，应用到上面所有数据源中
  datasource:
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    logSlowSql: true
  redis: 
    database: 1
    host: 127.0.0.1
    port: 6379
    password: admin
    timeout: 3000
    pool:
      max-active: 5000
      max-wait: 1000
      max-idle: 500
      min-idle: 50
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    pool:
      enabled: false
      max-connections: 50
      expiry-timeout: 10000
      idle-timeout: 30000

server:
  port: 8099
  contextPath: /
#spring.mvc.view.prefix=/WEB-INF/jsp/
#spring.mvc.view.suffix=.jsp

#registerWithEureka表示eureka中心不会自己注册自己
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/





---
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://localhost:3306/sptwin?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: admin
    driverClassName: com.mysql.jdbc.Driver





